const activities=['হয়গ্ৰীব শঙ্খগ্ৰীব বধ','কুৱালশ্ব্য উপাখ্যান, উজ্জুনাসুৰ বধ','সীতা হৰণ বালী বধ','মৎস্য অৱতাৰ, চাৰি বেদ উদ্ধাৰ','গজকেতু উপাখ্যান','বিপ্ৰ দামোদৰ আখ্যান'];
const $=s=>document.querySelector(s); const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fallback={contact_address:'B.P TINIALI,TEZPUR,ASSAM',contact_phone:'9394908170,6001291820',contact_email:'sanmilitayuvaksangha@gmail.com',facebook:'https://www.facebook.com/',instagram:'https://www.instagram.com/',whatsapp:'919394908170'};
let galleryItems=[];let galleryIndex=0;
async function get(u){try{const r=await fetch(u);return await r.json()}catch{return null}}
function observe(){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>io.observe(x))}
function openModal(items,i){galleryItems=items;galleryIndex=i;renderModal();$('#modal').classList.add('open');document.body.style.overflow='hidden'}function renderModal(){const x=galleryItems[galleryIndex];$('#modalImg').src=x.image||x;$('#modalText').textContent=x.caption||x.album||''}function closeModal(){$('#modal').classList.remove('open');document.body.style.overflow=''}function step(n){galleryIndex=(galleryIndex+n+galleryItems.length)%galleryItems.length;renderModal()}
function setupModal(){ $('#modalClose').onclick=closeModal;$('#modalPrev').onclick=()=>step(-1);$('#modalNext').onclick=()=>step(1);$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};document.addEventListener('keydown',e=>{if(!$('#modal').classList.contains('open'))return;if(e.key==='Escape')closeModal();if(e.key==='ArrowLeft')step(-1);if(e.key==='ArrowRight')step(1)});let sx=0;$('#modal').addEventListener('touchstart',e=>sx=e.touches[0].clientX);$('#modal').addEventListener('touchend',e=>{let dx=e.changedTouches[0].clientX-sx;if(Math.abs(dx)>50)step(dx<0?1:-1)})}
async function load(){
 const c=Object.assign({},fallback,await get('/api/content')||{});['facebook','instagram'].forEach(k=>{if(c[k]){$('#'+k).href=c[k]}else $('#'+k).style.display='none'});
 const wa=(c.whatsapp||fallback.whatsapp).replace(/\D/g,'');$('#whatsapp').onclick=()=>window.open(`https://wa.me/${wa}?text=${encodeURIComponent('Hello, I would like to join Sanmilita Yuvak Sangha, Tezpur.')}`,'_blank');
 const events=await get('/api/events')||[];events.sort((a,b)=>String(a.date).localeCompare(String(b.date)));const today=new Date().toISOString().slice(0,10);const upcoming=events.filter(e=>String(e.date)>=today),past=events.filter(e=>String(e.date)<today).reverse();const ordered=[...upcoming,...past];$('#eventGrid').innerHTML=ordered.length?ordered.map((e,i)=>`<article class="event" data-i="${i}"><span class="date">${esc(e.date)} · ${esc(e.time||'')}</span><h3>${esc(e.name)}</h3><p>${esc(e.venue||'')}</p><small>${esc(e.category||'')}</small></article>`).join(''):'<div class="empty">Events will appear here when published from the admin dashboard.</div>';
 const g=await get('/api/gallery')||[];galleryItems=g.map(x=>({image:x.image,caption:x.caption,album:x.album})).filter(x=>x.image);$('#galleryGrid').innerHTML=galleryItems.length?galleryItems.map((x,i)=>`<div class="gallery-item" data-i="${i}"><img loading="lazy" src="${esc(x.image)}" alt="${esc(x.caption||x.album||'Cultural memory')}"><span>${esc(x.caption||x.album||'')}</span></div>`).join(''):'<div class="empty">Gallery photos will appear here.</div>';document.querySelectorAll('.gallery-item').forEach(el=>el.onclick=()=>openModal(galleryItems,+el.dataset.i));
 const team=await get('/api/team')||[];$('#teamGrid').innerHTML=team.length?team.map(x=>`<article class="member"><h3>${esc(x.name)}</h3></article>`).join(''):`<article class="member"><h3>দলৰ সদস্যসকল</h3></article>`;
 const news=await get('/api/news')||[];news.sort((a,b)=>String(b.date).localeCompare(String(a.date)));const latest=news.slice(0,3);$('#newsGrid').innerHTML=latest.length?latest.map((x,i)=>`<article class="news-card" data-i="${i}"><time>${esc(x.date)}</time><h3>${esc(x.title_as||x.title_en)}</h3><span>Read full update →</span></article>`).join(''):'<div class="empty">News and updates will appear here.</div>';$('#viewAllNews').style.display=news.length?'block':'none';
 const p=$('#performanceGrid');p.innerHTML=activities.map((x,i)=>`<article class="performance" data-title="${esc(x)}" style="background-position:center ${i%2?'60%':'45%'}"><div><small>FEATURED PERFORMANCE · 0${i+1}</small><h3>${esc(x)}</h3><span>View photos →</span></div></article>`).join('');p.querySelectorAll('.performance').forEach(el=>el.onclick=()=>openModal(galleryItems.filter(x=>String(x.album||'').includes(el.dataset.title)||String(x.caption||'').includes(el.dataset.title)),0));
 observe();
}
function counters(){document.querySelectorAll('[data-count]').forEach(el=>{const n=+el.dataset.count;let start=0;const t=setInterval(()=>{start+=Math.max(1,Math.ceil(n/18));if(start>=n){start=n;clearInterval(t)}el.textContent=start+'+'},55)})}
let lastY=0;window.addEventListener('scroll',()=>{const y=scrollY;$('#nav').classList.toggle('hidden',y>lastY&&y>120);lastY=y;$('#top').classList.toggle('show',y>500)});$('#hamb').onclick=()=>$('#menu').classList.toggle('open');document.querySelectorAll('#menu a').forEach(a=>a.onclick=()=>$('#menu').classList.remove('open'));$('#top').onclick=()=>scrollTo({top:0,behavior:'smooth'});
$('#joinForm').onsubmit=async e=>{e.preventDefault();const r=await fetch('/api/membership',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});$('#joinMsg').textContent=r.ok?'আবেদন সফলভাৱে পঠিওৱা হ’ল।':'অনুগ্ৰহ কৰি পুনৰ চেষ্টা কৰক।';if(r.ok)e.target.reset()};
$('#viewAllNews').onclick=async()=>{const news=await get('/api/news')||[];news.sort((a,b)=>String(b.date).localeCompare(String(a.date)));openModal(news.map(x=>({image:x.image,caption:`${x.title_as||x.title_en} · ${x.date}\n\n${x.body_as||x.body_en||''}`})),0)};
setupModal();window.addEventListener('load',()=>{setTimeout(()=>$('#loader').classList.add('hide'),900);load();counters()});
